# Specify a base image

FROM node:16-alpine

# Install some dependencies

WORKDIR /usr/app
COPY ./package.json /usr/app
RUN npm install

COPY ./ /usr/app


# Default command

CMD ["npm", "run", "start"]

